name: 'Deployment'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  deployment:
    name: 'Deployment'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install front end deps
      run: npm ci
      working-directory: ./frontend
    - name: Build front end
      run: npm run build
      working-directory: ./frontend
